package names

// Curated wordlists for device handles. Rules: common English, 3–8 letters,
// easy to say over the phone, no slurs, no brands, no body parts, no
// near-duplicate spellings (gray/grey), no words that are both lists.

// Adjectives (first word).
var adjectives = []string{
	"able", "acid", "aged", "agile", "airy", "alert", "alpine", "amber",
	"ancient", "apricot", "aqua", "arctic", "autumn", "azure", "baked", "bold",
	"bonny", "brave", "breezy", "brief", "bright", "brisk", "bronze", "bubbly",
	"busy", "calm", "candid", "cheery", "chilly", "civil", "classic", "clever",
	"cloudy", "coastal", "cobalt", "copper", "coral", "cosmic", "cozy", "crimson",
	"crisp", "curious", "daring", "dapper", "dawn", "deep", "desert", "dewy",
	"dizzy", "docile", "dotted", "double", "dusky", "dusty", "eager", "early",
	"earthy", "easy", "electric", "emerald", "even", "exact", "fabled", "fair",
	"famous", "fancy", "fast", "feather", "fierce", "fine", "firm", "floral",
	"fluent", "foggy", "fond", "forest", "frosty", "funky", "gentle", "giant",
	"gilded", "glad", "gleaming", "glossy", "golden", "grand", "granite", "green",
	"happy", "hardy", "hazel", "hidden", "high", "hollow", "honest", "humble",
	"icy", "indigo", "inky", "iron", "ivory", "jade", "jolly", "jovial",
	"keen", "kind", "large", "lazy", "leafy", "lemon", "light", "lively",
	"local", "lofty", "loyal", "lucid", "lucky", "lunar", "magic", "major",
	"mango", "marble", "mellow", "merry", "mighty", "minor", "minty", "misty",
	"modern", "mossy", "muted", "nice", "nimble", "noble", "north", "novel",
	"oaken", "ocean", "olive", "opal", "orange", "pale", "peachy", "pearl",
	"pebble", "perky", "pine", "plaid", "plain", "plucky", "polar", "prime",
	"proud", "purple", "quick", "quiet", "rainy", "rapid", "rare", "regal",
	"ripe", "roaming", "robust", "rocky", "rosy", "round", "royal", "ruby",
	"rustic", "sable", "sandy", "scarlet", "serene", "sharp", "shiny", "silent",
	"silken", "silver", "sleek", "slim", "smart", "smooth", "snowy", "soft",
	"solar", "solid", "sonic", "spry", "stable", "starry", "steady", "steel",
	"stony", "stormy", "sturdy", "sunny", "swift", "tall", "tame", "tawny",
	"teal", "tender", "tidal", "tidy", "tiny", "topaz", "tranquil", "true",
	"trusty", "twin", "umber", "upbeat", "urban", "velvet", "verdant", "vivid",
	"warm", "wavy", "western", "wild", "windy", "winter", "wise", "witty",
	"wooden", "woolly", "young", "zesty",
}

// Nouns (second word).
var nouns = []string{
	"acorn", "alder", "anchor", "antler", "apple", "arrow", "aspen", "atlas",
	"badger", "bamboo", "banjo", "barley", "basil", "bay", "beacon", "bear",
	"beetle", "bell", "birch", "bison", "bobcat", "bonfire", "book", "breeze",
	"brook", "bridge", "cabin", "cactus", "camel", "canoe", "canyon", "caravan",
	"cardinal", "cascade", "castle", "cedar", "cello", "cherry", "cliff", "clover",
	"comet", "compass", "condor", "coral", "cosmos", "cotton", "cougar", "cove",
	"coyote", "crane", "cricket", "crow", "crystal", "cypress", "daisy", "deer",
	"delta", "dingo", "dolphin", "dome", "donkey", "dragon", "drum", "dune",
	"eagle", "echo", "ember", "falcon", "fern", "ferret", "fiddle", "finch",
	"fjord", "flame", "flint", "flute", "fox", "gazelle", "gecko", "geyser",
	"gibbon", "ginger", "glacier", "glade", "goose", "gorge", "grove", "gull",
	"harbor", "hare", "hawk", "hazel", "heron", "hickory", "hill", "horizon",
	"hornet", "horse", "hound", "husky", "ibis", "iceberg", "iris", "island",
	"jackal", "jaguar", "jasper", "jungle", "juniper", "kayak", "kestrel", "kettle",
	"kite", "koala", "lagoon", "lake", "lantern", "larch", "lark", "laurel",
	"lemur", "lily", "lion", "lizard", "llama", "lobster", "locust", "lotus",
	"lynx", "magnet", "magpie", "mantis", "maple", "marlin", "marmot", "meadow",
	"mesa", "meteor", "mole", "monsoon", "moose", "morning", "moth", "mountain",
	"mule", "mustang", "nebula", "nectar", "newt", "oasis", "ocelot", "orbit",
	"orchid", "osprey", "otter", "owl", "panda", "panther", "papaya", "parrot",
	"peak", "pelican", "penguin", "pepper", "petrel", "pheasant", "pigeon", "pika",
	"pine", "planet", "plum", "pond", "poppy", "prairie", "puffin", "puma",
	"quail", "quartz", "quill", "rabbit", "raccoon", "raven", "reef", "ridge",
	"river", "robin", "rocket", "rowan", "saffron", "sage", "salmon", "sequoia",
	"shark", "sierra", "sloth", "sparrow", "spruce", "squid", "starling", "stoat",
	"stone", "stork", "summit", "sundial", "swallow", "swan", "tapir", "terrace",
	"thistle", "tiger", "toucan", "trout", "tulip", "tundra", "turtle", "valley",
	"vine", "violet", "vulture", "walnut", "walrus", "wasp", "weasel", "whale",
	"willow", "wolf", "wombat", "wren", "yak", "zebra", "zephyr", "zinnia",
}
